### PR TITLE
Updated Liveview version to anything greater that 0.18.0 

### PR DESCRIPTION
**Pull request by dbhowmick**
Finally, Phoenix Liveview is 1.0!

Updated this project to use liveview 1.0 version and the ex_doc version to the latest version.

### CODE REVIEW

**Comment by benvp** [comment]
Thanks. Did you encounter any issues while using  it? Asking specificially about the use of `use CVA.Component` macros.

**Comment by dbhowmick** [comment]
Hi @benvp, I will check this specifically today and update the findings here.

**Comment by dbhowmick** [comment]
Hi @benvp, I tested it out in a working system with the following dependency:

```elixir
defp deps do
  [
    {:phoenix, "~> 1.7.11"},
    {:phoenix_html, "~> 4.1"},
    {:phoenix_live_reload, "~> 1.2", only: :dev},
    {:phoenix_live_view, "~> 1.0"},
    # Some mode additional dependencies
    # {:cva, "~> 0.2.1"},
    {:cva, path: "/Users/dipayan/work/personal/development/ex_cva"},
    {:tails, "~> 0.1.11"},
    {:nanoid, "~> 2.1.0"}
  ]
end
```
Use the `CVA.Component` macro inside a functional component with the following configuration:

```elixir
  use CVA.Component
  use Phoenix.Component

  variant :variant,
          [
            default: "bg-primary text-primary-foreground hover:bg-primary/90",
            destructive: "bg-destructive text-destructive-foreground hover:bg-destructive/90",
            outline:
              "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
            secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80",
            ghost: "hover:bg-accent hover:text-accent-foreground",
            link: "text-primary underline-offset-4 hover:underline"
          ],
          default: :default

  variant :size,
          [
            default: "h-10 px-4 py-2",
            xs: "h-7 rounded px-2",
            sm: "h-9 rounded-md px-3",
            lg: "h-11 rounded-md px-8",
            icon: "h-10 w-10"
          ],
          default: :default
```

Testing steps:
* Cleaned up the dependencies.
* Modified `mix.exs` to load the `ex_cva` dependency from the local path with the updated git branch.
* Compiled my application.
* Ran the application.
* Tested manually that all the components using the `CVA.component` macro work.

Please let me know if I should test this in any other way.

**Comment by benvp** [comment]
Thanks! :heart:  Will do a little testing by myself these days and create a release shortly afterwards.

**Review by benvp — APPROVED** [review]

**Pull request merged**
